### ISSUE TITLE
Change Ayah every new tab

### ISSUE THREAD

**Issue by MustafaAmer-1** [shahednasser/quran-extension#5]
Hello, thanks for this awesome extension,
I suggest to show up random ayah every time you open new tab, without pressing reload button at the left corner, just like Alathkar.
also you can add buttons to get to the next or previous ayah.

**Comment by shahednasser** [comment]
Hi, @MustafaAmer-1 thank you for using the extension and the suggestion. Problem is that some of these APIs are free and they have a limited amount of requests per minute, so if a user opens a few tabs consecutively, it will result in an error. That is why the time limit is present. Also, if the person has slow wifi then it will take time for the image, audio, and verse to load, which means they will constantly be opening blank tabs.

If you have other suggestions please let me know!
