### ISSUE TITLE
Problem with audio

### ISSUE THREAD

**Issue by MustafaAmer-1** [shahednasser/quran-extension#6]
when I open two tabs and make a reload in the second one, the audio of the first one changes to be the same as the second tab without change in the verse text.

**Comment by shahednasser** [comment]
Thank you for catching that! I'll make sure to work on a fix for it

**Comment by shahednasser** [comment]
This issue has been resolved and the fix will be available in version `2.0.6` of the extension. Thank you for submitting this bug!
