### ISSUE TITLE
Better Screenshots for Chrome Web Store

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/quran-extension#8]
I am not that great when it comes to design in general, and so the screenshots of the extension in the [Chrome Web Store](https://chrome.google.com/webstore/detail/quran-in-new-tab/hggkcijghhpkdjeokpfgbhnpecliiijg?hl=en&authuser=2) are lacking. It would be great if someone can design/work on something better. Something that showcases the features of the extension, but also looks nice.

Keep in mind that Chrome requires the screenshots' dimensions to be 1280x800.

Optionally, the following promo images are needed in case the app gets featured in the future. However, this is not required:
- Small image of dimensions 440x280
- Large image of dimensions 920x680
- Marquee image of dimensions 1400x560

**Comment by murtuzaalisurti** [comment]
Hey, can I work on this issue?

**Comment by shahednasser** [comment]
Hi @murtuzaalisurti of course! If you're still up for it let's do it with the changes you made, as I'll add the screenshots to the new version released.

I'll assign you to this issue. if you're not up to it anymore that's fine just let me know.

**Comment by murtuzaalisurti** [comment]
sure, I will design them and get back to you soon!

**Comment by murtuzaalisurti** [comment]
hey, should I create screenshots for this version or for the new release which will include the UI that I recently created?

**Comment by shahednasser** [comment]
we need the screenshot for the new release, but we'll release the release with the screenshots at the same time. So, you can take the screenshot from the development version.

**Comment by murtuzaalisurti** [comment]
Here's the first design! Let me know if this works!
https://www.figma.com/file/BeS1yVcSODO9OWHyILXoxr/Quran-Extension?node-id=0%3A1

**Comment by murtuzaalisurti** [comment]
@shahednasser  If you want the images, then I am uploading them right here:

Cover Image:

<img width="640" alt="cover_image_quran_extension" src="https://user-images.githubusercontent.com/68743212/145702398-8aa8a20f-716d-4fa5-bb79-63f2874c54a6.png">

Image 1:

![image_1](https://user-images.githubusercontent.com/68743212/145702434-1ec7ce3f-3aa8-4093-aa38-e94f714704db.png)

Image 2:

![image_2](https://user-images.githubusercontent.com/68743212/145702450-7ff658a3-813b-4302-a061-a21ea9f8c49c.png)

**Comment by shahednasser** [comment]
So sorry for the late reply @murtuzaalisurti those look great. I'll export the images with the needed dimensions from figma and submit the new version on the chrome store. Thank you for the amazing work!

**Comment by shahednasser** [comment]
Actually @murtuzaalisurti do you know how I can export them with the required sizes? I remember there was a way but I can't find it now.

**Comment by murtuzaalisurti** [comment]
> Actually @murtuzaalisurti do you know how I can export them with the required sizes? I remember there was a way but I can't find it now.

Just select an image in figma and find the Export option on right side panel all the way at the bottom. Click the plus icon and you can export the files. The files are already in the specified dimension. Just export them.

**Comment by murtuzaalisurti** [comment]
> Actually @murtuzaalisurti do you know how I can export them with the required sizes? I remember there was a way but I can't find it now.

The files are in 1280x800 dimension.

**Comment by shahednasser** [comment]
Yes I'm aware of that but is it possible to export them in the optional dimensions I mentioned above? If it's not that's fine but just checking

**Comment by murtuzaalisurti** [comment]
> Yes I'm aware of that but is it possible to export them in the optional dimensions I mentioned above? If it's not that's fine but just checking

Yes it's possible but for that we should create a new layer and overlap the image on that or we can create modified images which satisfy the given dimensions. If the aspect ratio is same then there is no problem.

**Comment by shahednasser** [comment]
no it's ok it's not necessary. I've uploaded the new version with the changes you made and screenshots and now it's undergoing the review process. Thank you for the great work!
